[package]
name = "alloy-rs-boilerplate"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.3.3", features = ["full"] }
eyre = "0.6.12"
tokio = { version = "1.40.0", features = ["full"] }
dotenv = "0.15.0"
